### PR TITLE
Feature login

### PR DESCRIPTION
**Pull request by sjaak1992**
# This pull request is all about: 

* made a signup component 
* created a custom hook to set values and errors
* made a separate file called "validate" - with all the info about the signup requirements 
*  styled the component 

p.s. : IBAN validation is not working yet and the link to the login component is still in the making 

Register

💟  Sjaak

### CODE REVIEW

**Comment by Reinoptland** [comment]
- The validation text might be a bit small
- My actual iBan does not pass the iBan validation -> regex is good just put ! in front of the check

Small styling things:

- Input fields run across the card, only some padding on the side
- Input fields and text are aligned to the left (except the "Already have an account text" that's centered
- Button is full width, maybe we can reuse Arnoud's button?
- Link text is the primary color (purple), it's blue still

Screenshot 2021-07-12 at 10 36 14
Screenshot 2021-07-12 at 10 36 17

BEM things

- form__input--label, is not really a modifier, consider form__label instead

Data format

In your formhook and in the `name` attributes of the form you have this data model
```js
{
        email:'',
        password:'',
        firstname:'',
        lastname:'',
        iban:''
}
```

But the api expects: 

```json
{
    "email": "rein@rein.com",
    "password": "abcd1234",
    "firstName": "Rein",
    "lastName": "Op 't Land",
    "iBan": "NL21INGB1234121234"
}
```

So we need to update `casing` of the data to match the api.

Still todo: 

- [x] Implement fixes for the small things above  
- [x] Send data to the api to create a new user
- [x] Make FormHook / Form elements into reusable things

**Review by Reinoptland — CHANGES_REQUESTED** [review]
See comment in the PR 😂

**Comment by sjaak1992** [comment]
# Changes made 🟡 :

* changed the to do's from review
* npm install axios to communicate with the server (to make requests and sign up/login new user)
* made an input component
* created a login in component 
* linked login with sign up 

Schermafbeelding 2021-07-13 om 15 57 54

**Review by Reinoptland — APPROVED** [review]
Looks good! 

It only says `Sign up` on the login button 😅

**Comment by Reinoptland** [comment]
Great work - really like the learning you did with FormHook and validate and making things reusable! 💪

**Review by Reinoptland — CHANGES_REQUESTED** [review]
I think there might be some bugs, I need to test this a little 😅

**Comment by sjaak1992** [comment]
Maybe tomorrow @abouman76 can show his testing skills?

**Comment by sjaak1992** [comment]
> Looks good!
> 
> It only says `Sign up` on the login button 😅

Whoops! I changed it!

**Comment by sjaak1992** [comment]
> I think there might be some bugs, I need to test this a little 😅

Maybe tomorrow @abouman76 can show his testing skills?

**Comment by abouman76** [comment]
ow yes, lets do an End-2-End test tomorrow!

Op di 13 jul. 2021 om 18:19 schreef sjaak1992 ***@***.***>:

**Comment by Reinoptland** [comment]
Small debug: 

- Added onsubmit handler for login
- Seperate validation function for login

**Review by Reinoptland — APPROVED** [review]
LGTM 👍

**Pull request merged**
